### ISSUE TITLE
LDR all over the place

### ISSUE THREAD

**Issue by melsom** [bruhautomation/ESP-MQTT-JSON-Multisensor#22]
Hello,

Is there any way to correct this? The sensor i stationary but the values seems to be up/down alot even though the median seems to be correct, looking at the 24h logs.

![image](https://user-images.githubusercontent.com/246733/27507571-3ea70c9a-58d2-11e7-86d6-f49fcbc45a80.png)

![image](https://user-images.githubusercontent.com/246733/27507578-686213a4-58d2-11e7-9e8e-91e736c6dee0.png)

**Comment by cooljimy84** [comment]
I get this when someone walks in front of the sensor. I was thinking of using a diffuser on top of it to try and level it out a bit.
I also have a 30 minute window where the sun bounces off cars going past and they reflect into the flat causing it to read higher for a second or so....

**Comment by jonathanweinberg** [comment]
Also, if you're using an LDR, `lux` is an arbitrary thing in that scale, you aren't getting true `lux` values.

**Comment by ntalekt** [comment]
I got this too and realized it was my ceiling fan throwing shadows all over the place. I moved the sensor to a place that isn't affected and mounted in an enclosure and it's been rock solid.

**Comment by Jizar07** [comment]
I got a different issue , my sensor works backwards, if its dark the numbers goes up to about 600 lux, if is bright is goes down to 33 lux. , I got the 4 pin sensor and got signal pin on AO (analog output) instead of DO (digital output). already tried switch AO and DO, but got the same result. any help would be greatly appreciated.

**Comment by cooljimy84** [comment]
correct (well for me as well) so darkness for my sensor is 900 LUX and bright light is 20 odd.

**Comment by rdbahm** [comment]
@Jizar07 At least with an LDR, this happens if  your ground and 3v are swapped.

**Comment by mikewebb70** [comment]
> 
> 
> Also, if you're using an LDR, `lux` is an arbitrary thing in that scale, you aren't getting true `lux` values.

Thanks.  came here to ask about that as I found it just gave me a voltage reading between 0-1024 (as expected when using A0).  So I wrote a template in HA that turned it into a % value.

**Comment by jonathanweinberg** [comment]
@mikewebb70 - you should share that template :)

**Comment by mikewebb70** [comment]
> @mikewebb70 - you should share that template :)

You are right I should have, it's nothing special.  Here is my light sensor Home Assistant yaml entry

```yaml
- platform: mqtt
  name: "lux office"
  state_topic: "tele/labmcu/SENSOR"
  unit_of_measurement: "%"
  #value_template: "{{ value_json['ANALOG'].A0 }}"
  value_template: "{{ (value_json['ANALOG'].A0|float/1024*100|float)|round(0) }}"
  availability_topic: "tele/labmcu/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
```
