### ISSUE TITLE
LED Flash not using length being set

### ISSUE THREAD

**Issue by devinjparsons** [bruhautomation/ESP-MQTT-JSON-Multisensor#35]
I have a weird issue where I set the led to flash for 10 seconds, but the mqtt message that is sent has the flash set to 2, no matter the value I set.  Have you seen this issue?

*Edit: looks like not even brightness is being ignored too.

```
action:
    service: light.turn_on
      data:
        entity_id: light.master_led
        color_name: red
        brightness: 100
        flash: 10

Message arrived [(topic)] {"state": "ON", "color": {"r": 255, "g": 0, "b": 0}, "flash": 2, "brightness": 255}
```
